language: rust
os:
    - linux
env:
    global:
        - secure: eInI3uby+kKTDX5OX5xsIakbIa0fL9vJzJ0M23YxeLITNDyGFk7EFAGrUzfRZqJNLIn6Oba+2FuImoz78KbiSqfZjDViVTHL5iz5ovp5RtDeblIxS6ZNs8BqSgsR+hKFIADyBzPquiBEuuUk4ybIgjoNp2Z3STvdD0xlaiNL5Lc=
script:
    - cargo build -v
    - cargo test  -v
    - cargo doc   -v
after_script:
    - cp -R target/doc doc
    - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
    - rm -r doc
