language: rust
os:
    - linux
env:
    global:
        - secure: h2qC3ycZtg5+skxur3yivES5mCUjaKTmQkfo3ByCg+SzqkGBXRWttTQwWSYwoZKNAlVhBaR7EkWhsswCTLU0AwNz449J6lQIHV5q6TP0jYZWHQ7AEOpITcXpTl0VzYRezGPD/HxcPKIXOeyC7JnV3GHYizBAhXJb+9OfMIwvMF0=
script:
    - cargo build -v
    - cargo test  -v
    - cargo doc   -v
after_script:
    - cp -R target/doc doc
    - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
    - rm -r doc
